services:
  # 1. Database Service (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: shortener_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=shortener
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Caching Service (Redis)
  cache:
    image: redis:7-alpine
    container_name: shortener_redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning # Basic persistence config

volumes:
  postgres_data: